"""empty message

Revision ID: 0940fb51a3ed
Revises: 4d3f4909baad
Create Date: 2023-01-07 20:10:08.464249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0940fb51a3ed'
down_revision = '4d3f4909baad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_vice_user_id_fkey', 'user_vice', type_='foreignkey')
    op.drop_constraint('user_vice_vice_id_fkey', 'user_vice', type_='foreignkey')
    op.create_foreign_key(None, 'user_vice', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_vice', 'vices', ['vice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_vice', type_='foreignkey')
    op.drop_constraint(None, 'user_vice', type_='foreignkey')
    op.create_foreign_key('user_vice_vice_id_fkey', 'user_vice', 'vices', ['vice_id'], ['id'])
    op.create_foreign_key('user_vice_user_id_fkey', 'user_vice', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
