"""added messages table

Revision ID: 6165b6274de5
Revises: 0940fb51a3ed
Create Date: 2023-01-08 17:58:22.638126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6165b6274de5'
down_revision = '0940fb51a3ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1_id', sa.Integer(), nullable=True),
    sa.Column('user_2_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.CheckConstraint('owner_id = user_2_id OR owner_id = user_1_id'),   
    sa.ForeignKeyConstraint(['user_1_id', 'user_2_id'], ['conversations.user_1_id','conversations.user_2_id'], ondelete='CASCADE'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='uix_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_unique_constraint("uix_2", "conversations", ["user_1_id", "user_2_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
