"""removed unique constraint from message foreign key

Revision ID: e0a71688c307
Revises: e2e2b8e6de01
Create Date: 2023-01-08 23:39:59.709619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a71688c307'
down_revision = 'e2e2b8e6de01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_2', 'message', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_2', 'message', ['user_1_id', 'user_2_id'])
    # ### end Alembic commands ###
